---
- name: Create Kubernetes Keypair
  ec2_key:
    name: "{{ kubernetes_keypair }}"
    key_material: "{{ item }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  with_file: ~/.ssh/id_rsa.pub