---
- name: Create security group
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: "{{ item.protocol }}"
        ports: "{{ item.ports }}"
        cidr_ip: "{{ item.cidr_ip }}"
  with_items: "{{ security_groups }}"

- name: Provision VM
  ec2:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ item.keypair }}"
    group: "{{ item.group }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.image }}"
    instance_tags:
      vm: sandbox
    exact_count: 1
    count_tag: dev
    wait: true
  register: ec2
  with_items: "{{ ec2_instance }}"