---
- name: Create AWS Virtual Private Cloud
  ec2_vpc_net:
    name: "kubernetes-vpc-{{ aws_cluster_name }}"
    state: present
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    dns_hostnames: yes
    dns_support: yes
    tags:
      Name: "kubernetes-vpc-{{ aws_cluster_name }}"
  register: vpc

- name: set fact vpc_id
  set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

- name: allocate a new elastic IP inside a VPC
  ec2_eip:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    in_vpc: yes
    public_ip: yes
  register: eip
  with_sequence: count=2

- name: set fact allocation_id
  set_fact:
    allocation_ids: "{{ eip.results|map(attribute='allocation_id')|list }}"

- name: Create VPC Internet Gateway
  ec2_vpc_igw:
    vpc_id: " {{ vpc_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    tags:
      Name: "kubernetes-internetgw-{{ aws_cluster_name }}"
  register: igw
  ignore_errors: yes

- name: Gather facts about a filtered list of Internet Gateways
  ec2_vpc_igw_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
        "tag:Name": "kubernetes-internetgw-{{ aws_cluster_name }}"
  register: igw_facts

- name: set fact igw_id
  set_fact:
    igw_id: "{{ igw_facts.internet_gateways[0].internet_gateway_id }}"

- name: Create public VPC Subnet
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    vpc_id: " {{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.availability_zone }}"
    map_public: yes
    resource_tags:
      Name: "kubernetes-public-subnet-{{ aws_cluster_name }}"
      "kubernetes.io/cluster/mydevopscluster": member
  register: kubernetes_public_subnet
  with_items: "{{ aws_subnet_public }}"

- ec2_vpc_subnet_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
      "tag:Name": "kubernetes-public-subnet-{{ aws_cluster_name }}"
  register: public_subnet_facts

- name: set fact kubernetes_public_subnet
  set_fact:
    public_subnet_ids: "{{ public_subnet_facts.subnets|map(attribute='id')|list }}"

- name: print subnet_ids
  debug:
    var: public_subnet_ids

- name: Create new nat gateway using an allocation-id
  ec2_vpc_nat_gateway:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    subnet_id: "{{ item[0] }}"
    allocation_id: "{{ item[1] }}"
    wait: yes
  with_items:
    - "{{ subnet_ids }}"
    - "{{ allocation_ids }}"

- name: Get all nat gateways with specific filters
  ec2_vpc_nat_gateway_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
      subnet-id: "{{ item }}"
      state: ['available']
  register: nat_gateway_facts
  with_items: "{{ public_subnet_ids }}"

- name: Set fact Nat Gateways IDs
  set_fact:
    nat_gateway_ids: "{{ nat_gateway_facts.nat_gateways|map(attribute='nat_gateway_id')|list }}"

- name: Create private VPC Subnet
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    vpc_id: " {{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.availability_zone }}"
    resource_tags:
      Name: "kubernetes-private-subnet-{{ aws_cluster_name }}"
      "kubernetes.io/cluster/mydevopscluster": member
  register: kubernetes_private_subnet
  with_items: "{{ aws_subnet_private }}"

- ec2_vpc_subnet_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
      "tag:Name": "kubernetes-private-subnet-{{ aws_cluster_name }}"
  register: private_subnet_facts

- name: set fact kubernetes_public_subnet
  set_fact:
    private_subnet_ids: "{{ private_subnet_facts.subnets|map(attribute='id')|list }}"

- name: print subnet_ids
  debug:
    var: private_subnet_ids

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    tags:
      Name: "kubernetes-public-routetable-{{ aws_cluster_name }}"
    subnets: "{{ item }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_id }}"
  register: public_route_table
  with_items: "{{ public_subnet_ids }}"

- name: Set up NAT-protected route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    tags:
      Name: "kubernetes-private-routetable-{{ aws_cluster_name }}"
    subnets: "{{ item[0] }}"
    routes:
      - dest: 0.0.0.0/0
        instance_id: "{{ item[1] }}"
  register: nat_route_table
  with_items:
    - "{{ private_subnet_ids }}"
    - "{{ nat_gateways_ids }}"