---
- name: Create AWS Virtual Private Cloud
  ec2_vpc_net:
    name: "kubernetes-vpc-{{ aws_cluster_name }}"
    state: present
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    dns_hostnames: yes
    dns_support: yes
    tags:
      Name: "kubernetes-vpc-{{ aws_cluster_name }}"
  register: vpc

- name: print vpc output
  debug:
    var: vpc

- name: set fact vpc_id
  set_fact:
    vpc_id: "{{ vpc.id }}"

- name: allocate a new elastic IP inside a VPC
  ec2_eip:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    in_vpc: yes
  register: eip

- name: print eip output
  debug:
    var: vpc

- name: Create VPC Internet Gateway
  ec2_vpc_igw:
    vpc_id: " {{ vpc_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    tags:
      Name: "kubernetes-internetgw-{{ aws_cluster_name }}"
  register: igw

- name: print igw output
  debug:
    var: igw

- name: set fact igw_id
  set_fact:
    igw_id: "{{ igw.id }}"

- name: Create public VPC Subnet
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    vpc_id: " {{ vpc_id }}"
    cidr: "{{ aws_cidr_subnets_public }}"
    az: "{{ item }}"
    map_public: yes
    resource_tags:
      Name: "kubernetes-public-subnet-{{ aws_cluster_name }}"
      "kubernetes.io/cluster/mydevopscluster": member
  register: kubernetes_public_subnet
  with_items: "{{ aws_availability_zones }}"

