---
- name: Create AWS security group
  ec2_group:
    name: "{{ ec2_security_group_name }}"
    description: "{{ ec2_security_group_desc }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: tcp
        ports:
          - 80
          - 8080
          - 22
        cidr_ip: 0.0.0.0/0