---
- name: Provision Kubernetes VMs
  ec2:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ ec2_keypair }}"
    group: "{{ ec2_security_group_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_tags:
      kube: "{{ item }}"
    exact_count: 1
    count_tag: dev
    wait: true
  register: ec2
  with_items: "{{ kubernetes_cluster }}"

- name: print provision output
  debug:
    var: ec2