---
- action:
    module: ec2_elb_facts
    names: "kubernetes-elb-{{ aws_cluster_name }}"
  register: elb_facts

- name: Set ELB ID
  set_fact:
    elb_id: "{{ elb_facts.ec2_elbs|map(attribute='id')|list }}"