---
- ec2_vpc_subnet_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
      "tag:Name": "kubernetes-public-subnet-{{ aws_cluster_name }}"
  register: subnet_facts

- name: print subnet_facts
  debug:
    var: subnet_facts

- name: set fact kubernetes_public_subnet
  set_fact:
    subnet_ids: "{{ subnet_facts.subnets|map(attribute='id')|list }}"
#    subnet_ids: "{{ subnet_facts|map(attribute='subnets.0.id')|list }}"

- name: print subnet_ids
  debug:
    var: subnet_ids