---
- ec2_instance_facts:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    filters:
      "tag:Name": "kubernetes-bastion-{{ aws_cluster_name }}"
  register: ec2_master_instances

- name: debug ec2_master_instances
  debug:
    var: ec2_master_instances

- name: Set ec2_master_instances
  set_fact:
    kubernetes_master_ids: "{{ ec2_master_instances|map(attribute='instance_ids')|list }}"

- action:
    module: ec2_elb_facts
    names: "kubernetes-elb-{{ aws_cluster_name }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  register: elb_facts

- name: print elb_facts
  debug:
    var: elb_facts

- name: Set elb_name
  set_fact:
    elb_name: "{{ elb_facts.elbs|map(attribute='name')|list }}"

- name: Instance Register
  ec2_elb:
    instance_id: "{{ item }}"
    ec2_elbs: "{{ elb_name }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    wait: yes
  with_items: "{{ kubernetes_master_ids }}"