---
- action:
    module: ec2_elb_facts
    names: "kubernetes-elb-{{ aws_cluster_name }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  register: elb_facts

- name: print elb_facts
  debug:
    var: elb_facts

- name: Set elb_name
  set_fact:
    elb_name: "{{ elb_facts.elbs|map(attribute='name')|list }}"

- name: Instance Register
  local_action:
    module: ec2_elb
    instance_id: "{{ item }}"
    ec2_elbs: "{{ elb_name }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
  with_items: "{{ kubernetes_master_ids }}"