---
- name: Provision Bastion Instance
  ec2:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ kubernetes_keypair }}"
    group_id: "{{ sg_kubernetes_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_tags:
      Name: "kubernetes-bastion-{{ aws_cluster_name }}"
      Cluster: "{{ aws_cluster_name }}"
      Role: "bastion"
      kubespray-role: "bastion"
    count: 1
    wait: true
    vpc_subnet_id: "{{ public_subnet_id }}"
  register: ec2_bastion


- name: Provision Kubernetes Master Instances
  ec2:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ kubernetes_keypair }}"
    group_id: "{{ sg_kubernetes_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_profile_name: "{{ ec2_instance_profile_name_kube_master }}"
    instance_tags:
      Name: "kubernetes-bastion-{{ aws_cluster_name }}"
      Cluster: "{{ aws_cluster_name }}"
      Role: "master"
      kubernetes.io/cluster/mydevopscluster: "member"
      kubespray-role: "kube-master, etcd"
    count: 3
    wait: true
    vpc_subnet_id: "{{ private_subnet_id }}"
  register: ec2_kubernetes_master

- name: print ec2_kubernetes_master
  debug:
    var: ec2_kubernetes_master

- name: Set Kubernetes Master IDs
  set_fact:
    kubernetes_master_ids: "{{ ec2_kubernetes_master|map(attribute='instance_ids')|list }}"

- action:
    module: ec2_elb_facts
    names: "kubernetes-elb-{{ aws_cluster_name }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
  register: elb_facts

- name: Set ELB ID
  set_fact:
    elb_id: "{{ elb_facts.ec2_elbs|map(attribute='id')|list }}"

- name: Instance Register
  local_action:
    module: ec2_elb
    instance_id: "{{ item }}"
    ec2_elbs: "{{ elb_id }}"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
  with_items: "{{ kubernetes_master_ids }}"

- name: Provision Kubernetes Node Instances
  ec2:
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ kubernetes_keypair }}"
    group_id: "{{ sg_kubernetes_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_profile_name: "{{ ec2_instance_profile_name_kube_node }}"
    instance_tags:
      Name: "kubernetes-bastion-{{ aws_cluster_name }}"
      Cluster: "{{ aws_cluster_name }}"
      Role: "worker"
      kubernetes.io/cluster/mydevopscluster: "member"
      kubespray-role: "kube-node"
    count: 3
    wait: true
    vpc_subnet_id: "{{ private_subnet_id }}"
  register: ec2_kubernetes_node