---
packages:
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - nano
    - wget
    - python-pip
    - python-netaddr

python_libs:
    - boto
    - boto3