---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: install packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"