---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user:
    name: ubuntu
    groups: wheel
    append: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: install packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: Add Ansible Repository
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present

- name: update apt
  apt:
    name: "*"
    state: latest

- name: install ansible
  apt:
    name: ansible
    state: installed