---
- name: Create AWS security group for ELB
  ec2_group:
    name: "{{ aws_lb_security_group_name }}"
    description: "AWS ELB SG"
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    vpc_id: #TODO
    rules:
      - proto: tcp
        from_port: 6443
        to_port: 6443
        cidr_ip: 0.0.0.0/0
        group_name: aws-allow-api-access
        group_desc: "Allow API Access"
    rules_egress:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
        group_name: aws-allow-api-egress
        group_desc: "Allow API Egress"
  register: elb_sg

- name: debug SG
  debug:
    var: elb_sg

- local_action:
  module: ec2_elb_lb
  name: "kubernetes-elb-{{ aws_cluster_name }}"
  state: present
  region: "{{ ec2_region }}"
  ec2_access_key: "{{ ec2_access_key }}"
  ec2_secret_key: "{{ ec2_secret_key }}"
  security_group_ids: 'sg-123456, sg-67890'
  subnets: 'subnet-123456,subnet-67890'
  zones:
    - eu-central-1a
    - eu-central-1b
  listeners:
    - protocol: tcp
      load_balancer_port: 6443
      instance_port: 6443