---
- name: Create new Elastic Loadbalancer for Kubernetes API
  elb_classic_lb:
    name: "kubernetes-elb-{{ aws_cluster_name }}"
    state: present
    region: "{{ ec2_region }}"
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    security_group_ids: "{{ sg_elb_id }}"
    subnets: "{{ public_subnet_id }}"
    zones: "{{ item.availability_zone }}"
    connection_draining_timeout: 400
    idle_timeout: 400
    listeners:
      - protocol: tcp
        load_balancer_port: 6443
        instance_port: 6443
    health_check:
      ping_protocol: tcp # options are http, https, ssl, tcp
      ping_port: 6443
      response_timeout: 5 # seconds
      interval: 30 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 2
    tags:
      Name: "kubernetes-elb-{{ aws_cluster_name }}"
  register: elb
  with_items: "{{ aws_subnet_public }}"