---
block:
  - name: Create admin user group
    group:
      name: admin
      system: yes
      state: present

  - name: Create Ansible user
    user:
      name: ansible
      shell: /bin/bash
      comment: "Ansible management user"
      home: /home/ansible
      createhome: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Add Ansible user to admin group
    user:
      name: ansible
      groups: admin
      append: yes

  become: yes
  become_method: sudo