---
- name: Configure Ansible VM for Kubernetes Install
  hosts: tag_vm_ansible
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
  roles:
    - ansible_setup