---
- name: Configure Ansible VM
  hosts: tag_vm_ansible
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
  roles:
    - ansible_setup
    - aws_kubernetes_keypair