---
- name: Create AWS Security Groups
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - aws_security_group