---
- name: Setup AWS for Kubernetes Install
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - aws_kubernetes_iam
    - aws_vpc
    - aws_security_group
    - aws_loadbalancer
    - aws_provision_kubernetes_cluster