---
- name: Configure Ansible VM for Kubernetes Install
  hosts: tag_vm_kubernetes
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - vm_update