---
- name: Configure Ansible VM for Kubernetes Install
  hosts: tag_vm_ansible
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - kubernetes_prepare