---
- name: Configure Ansible VM for Kubernetes Install
  hosts: tag_Role_bastion, tag_Role_master, tag_Role_worker
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - vm_update