---
- name: Set Authorization
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - generate_ssh_keys
    - aws_kubernetes_keypair