---
- name: Create Kubernetes VMs on AWS
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  roles:
    - provision_kubernetes_cluster