---
- name: Setup localhost for AWS
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../vars/environment.yml
    - ../vars/credentials.yml
  roles:
    - setup_localhost