---
- name: Stop AWS Instances
  hosts: local
  connection: localhost
  gather_facts: False
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/credentials.yml
    - ../vars/ec2.yml
  tasks:
    - name: Stop the sandbox instances
      ec2:
        region: '{{ ec2_region }}'
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        state: stopped
        instance_tags:
          vm: kubernetes
        wait: True